version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5005/
    networks:
      - project-net

  backend:
    build: ./backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    networks:
      - project-net
      - default # ✅ Thêm network default để kết nối với data-v2

volumes:
  sqlvolume:


networks:
  project-net:
