version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:5005/
    networks:
      - project-net

  backend:
    build: ./backend
    ports:
      - "5005:5005"
    env_file:
      - ./backend/.env
    depends_on:
      - mssql
    networks:
      - project-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "YourStrong@Passw0rd" # Trùng với .env
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - project-net

volumes:
  sqlvolume:


networks:
  project-net:
    driver: bridge
